### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by ackushiw** [ackushiw/mood-organ#1]
I think we should only have twitter and facebook and possibly google authentication for users... saves use from verifying email addresses

**Comment by peterwillis** [comment]
Take out the 'password' option in config.js, then alter the login-modal view. Delete the unused fields.

**Comment by ackushiw** [comment]
For some reason the login isn't working for me

**Comment by peterwillis** [comment]
Yes I noticed that too... I will investigate.

**Comment by ackushiw** [comment]
I found the Problem. We had set up the LoginCtrl controller to be activated when the route is /login. But the login button was just opening the modal and not changing the route.

**Comment by ackushiw** [comment]
Can't work out the log out though... I would have thought that was an easier problem

**Comment by ackushiw** [comment]
Worked it out just need a $ in auth.$logout()
