### ISSUE TITLE
Nav Bar

### ISSUE THREAD

**Issue by ackushiw** [ackushiw/mood-organ#4]
I'm thinking we could probably delete the nav bar and integrate it with the main search area

**Comment by peterwillis** [comment]
Yes I agree. The mood creation form is currently in the left hand column, but we can't see it because we can't login :-/

**Comment by ackushiw** [comment]
I've integrated it into the middle. I'm thinking that we use it as little as possible trying to keep the app to one page. if we need extra info we can provide them with modals that the nav links to
